addpath('/media/yue/make_nwb/matnwb/')

rawFile = '/media/knox/glymphatic/gly_Rat/23-09-25/particles-art1-down-71min/Image_0001_0001.raw';
nwbPath = '/media/knox/glymphatic/nwb_files_keelin/gly_rat_23-09-25_particles_art1_down_71min.nwb';
subjectID = 'r-2023-9-25';
nwb = NwbFile( ...
    'general_experiment_description', 'PTV KD', ...
    'session_description', 'particles, ECG, respiration',...
    'identifier', 'gly_rat_23-09-25_particles_art1_down_71min', ...
    'session_start_time', datetime(2023, 9, 25, 0, 0, 0, 'TimeZone', 'EST'), ...
    'general_experimenter', 'Ladron de Guevara, Antonio', ... % optional
    'general_session_id', 'rat_23-09-25_particles_art1_down_71min', ... % optional
    'general_institution', 'University of Rochester', ... % optional
    'general_keywords', 'Glymphatic, Perivascular space, Periarterial space, Cerebrospinal fluid.' ...
);

%%
[img,coords,info] = read_raw(rawFile);
width = length(coords.X);
height = length(coords.Y);
nFrames = length(coords.T);
nChannels = info.NumCh;
samplingRate = info.FrameRate;

movieData = zeros(height, width, nFrames, nChannels, 'uint16');
for k = 1:nChannels
    movieData(:,:,:,k) = img{k};
end

movieData = types.untyped.DataPipe( ...
    'data', permute(movieData, [3,1,2,4]), .....
    'chunkSize', [100, height, width, nChannels], ...
    'axis', 1 ...
);

imageSeries = types.core.ImageSeries( ...
    'data', movieData, ...
    'description', 'movie', ...
    'data_resolution', single(info.umperpix), ...
    'data_unit', 'umperpix', ...
    'starting_time', 0.0, ... 
    'starting_time_rate', samplingRate ...
);

% subject info
ageDays = 78;
ageDays = 'P' + string(ageDays) + 'D';
subject = types.core.Subject( ...
    'subject_id', subjectID, ...
    'age', char(ageDays), ...
    'description', 'Sprague Dawley rat from Charles River.', ... % optional, but preferred by inspector
    'species', 'Rattus norvegicus', ... % Subject species 'Mouse' should be in latin binomial form, e.g. 'Mus musculus' and 'Homo sapiens'
    'sex', 'M', ...
    'strain', '001' ...
);
nwb.general_subject = subject;
nwb.acquisition.set('Movies', imageSeries);
%%
nwbExport(nwb, nwbPath);