addpath("matnwb\")

mat = load('C:\Users\yzhao\Desktop\vessel-diameter-pulsatility-quantification\Qinwen_6th_March.mat');
nwbPath = 'C:\Users\yzhao\Desktop\vessel-diameter-pulsatility-quantification\03122024-m4-baseline.nwb';
nwb = NwbFile( ...
    'general_experiment_description', 'Vessel diameter and pulsatility measurement.', ...
    'session_description', 'the mouse skull was thinned at the area of the middle cerebral artery (MCA) and fitted with a head plate for fixation.',...
    'identifier', 'Qinwen_6th_March_03122024-m4-baseline', ...
    'session_start_time', datetime(2024, 3, 12, 0, 0, 0, 'TimeZone', 'EST'), ...
    'general_experimenter', 'Huang, Qinwen', ... % optional
    'general_session_id', '03122024-m4-baseline', ... % optional
    'general_institution', 'University of Rochester', ... % optional
    'general_keywords', 'Vessel diameter, Radon transform, full width at half maximum, vessel pulsation, image analysis' ...
);

video = mat.img_1;
[low, high] = bounds(video, 'all');
%video = permute(video,[3 1 2]);
[height, width, ~] = size(video);
videoData = types.untyped.DataPipe( ...
    'data', video, .....
    'chunkSize', [height, width, 1] ...
);

microscope_images = types.core.ImageSeries( ...
    'data', videoData, ...
    'description', '16-bit grayscale movie of a pial vessel', ...
    'data_unit', 'n.a.', ...
    'starting_time_rate', 30, ...
    'starting_time', 0.0 ...
);

% subject info
subject = types.core.Subject( ...
    'subject_id', '031224_M4', ...
    'age', 'P2M', ...
    'description', 'Before the imaging, the mouse was anesthetized with ketamine and xylazine cocktail (80 mg/kg, 10 mg/kg), then retro-orbital injected with fluorescent tracer (0.1 ml, 1%, albumin from Bovine serum 647, Thermo Fisher Scientific catalog: A34785)', ... % optional, but preferred by inspector
    'species', 'Mus musculus', ... % Subject species 'Mouse' should be in latin binomial form, e.g. 'Mus musculus' and 'Homo sapiens'
    'sex', 'M', ...
    'strain', 'C57BL/6' ...
);
 
nwb.acquisition.set('Movies', microscope_images);
nwb.general_subject = subject;
nwbExport(nwb, nwbPath);

%{
mat = load('C:\Users\yzhao\Desktop\vessel-diameter-pulsatility-quantification\F15BC-19102023_im_1.mat');
nwbPath = 'C:\Users\yzhao\Desktop\vessel-diameter-pulsatility-quantification\F15BC-19102023.nwb';
nwb = NwbFile( ...
    'general_experiment_description', 'Vessel diameter and pulsatility measurement.', ...
    'session_description', 'a wild-type mouse skull was thinned at the area of the middle cerebral artery (MCA) and fitted with a head plate for fixation.',...
    'identifier', '202309_Hashmat-OCT.2023-F15BC-19102023', ...
    'session_start_time', datetime(2023, 10, 19, 8, 0, 0, 'TimeZone', 'CET'), ...
    'general_experimenter', 'Ghanizada, Hashmat ', ... % optional
    'general_session_id', 'F15BC-19102023', ... % optional
    'general_institution', 'University of Copenhagen', ... % optional
    'general_keywords', 'Vessel diameter, Radon transform, full width at half maximum, vessel pulsation, image analysis' ...
);

video = mat.img;
[low, high] = bounds(video, 'all');
%video = permute(video,[3 1 2]);
[height, width, ~] = size(video);
videoData = types.untyped.DataPipe( ...
    'data', video, .....
    'chunkSize', [height, width, 1] ...
);

microscope_images = types.core.ImageSeries( ...
    'data', videoData, ...
    'description', '16-bit grayscale movie of a pial vessel', ...
    'data_unit', 'n.a.', ...
    'starting_time_rate', 54.47, ...
    'starting_time', 0.0 ...
);

% subject info
subject = types.core.Subject( ...
    'subject_id', 'F15', ...
    'age', 'P9W/P16W', ...
    'description', 'wild-type mouse', ... % optional, but preferred by inspector
    'species', 'Mus musculus', ... % Subject species 'Mouse' should be in latin binomial form, e.g. 'Mus musculus' and 'Homo sapiens'
    'sex', 'F', ...
    'strain', 'C57BL/6J' ...
);
 
nwb.acquisition.set('Movies', microscope_images);
nwb.general_subject = subject;
nwbExport(nwb, nwbPath);
%}