mouseDataFile = 'C:\Users\yzhao\Desktop\AER_Manuscript_Data\micedata.json'; % filename in JSON extension 
miceData = jsondecode(fileread(mouseDataFile));

metadataFile = 'C:\Users\yzhao\Desktop\AER_Manuscript_Data\Figure1+S1\water_intoxication.json'; % filename in JSON extension 
metadata = jsondecode(fileread(metadataFile));

nwbPath = 'C:\Users\yzhao\Desktop\AER_Manuscript_Data\nwb_files\Figure1+S1';

mice = fieldnames(metadata);
for i = 1:numel(mice)
    mouseID = mice{i};
    sessionMetadata = metadata.(mouseID);
    mouseData = miceData.(mouseID);

    nwb = NwbFile( ...
        'general_experiment_description', mouseData.Experiment, ...
        'session_description', sessionMetadata.Experiment, ... % optional, but required by inspector
        'general_session_id', mouseID, ...
        'identifier', mouseID, ...
        'session_start_time', datetime(sessionMetadata.EXPDate), ...
        ...'general_experimenter', sessionMetadata.Experimenter, ... %optional
        'general_institution', 'University of Rochester Medical Center; University of Copenhagen', ... % optional, but preferred by inspector
        'general_keywords', 'Astrocyte endfeet, glymphatic system, aquaporin-4, fluorescent microscopy, brain edema' ...
    );

    ageDays = mouseData.AgeDays;
    ageDays = ['P' num2str(ageDays) 'D'];
    subject = types.core.Subject( ...
        'subject_id', mouseID, ...
        'age', ageDays, ...
        'description', [ ...
            'Group: ' sessionMetadata.group '; ' ...
            'Time Drug: ' sessionMetadata.TIMEDRUG '; ' ...
            'Time Water: ' sessionMetadata.TimeWater '; '...
            'Time Death: ' sessionMetadata.timeDeath '; ' ...
            'Survival: ' sessionMetadata.Survival
        ], ... % optional, but preferred by inspector
        'species', 'Mus musculus', ... % Subject species 'Mouse' should be in latin binomial form, e.g. 'Mus musculus' and 'Homo sapiens'
        'sex', upper(mouseData.Sex), ...
        'genotype', mouseData.Genotype ...
    );
    nwb.general_subject = subject;
    nwbExport(nwb, fullfile(nwbPath, [mouseID '.nwb']));
end